"""中文版论文图的图内文字词典（与 scripts/m5_figures_i18n.py 配套）。

* ``TRANS``  整串映射（标题、注释、图例条目、分类刻度）。
* ``PHRASES`` 词级替换（先长后短），用于拼装串与单位。
* ``IDENT``  数据标识符：保持原样，且不报"未翻译"（包名、种子名、规则名等）。

词典由 ``m5_figures_i18n.py --collect`` 的输出逐条建立（413 条图内文字）。
"""
from __future__ import annotations

import re

# 数据标识符族（包名/运行名/规则名）：保持原样，不报未翻译
_IDENT_RE = re.compile(
    r"^(?:m5auto|pkg|annotate_pkg|collect|dev9|t14|base6x|seed42|seg_model|"
    r"s\d\d|a\d{1,2}|c\d|e\d)[\w\-\.]*$")

IDENT = {
    "n/a", "p50", "p95", "R2", "R3", "R3 pool", "R3 pool B", "t14", "dev",
    "base", "base6x", "final", "degraded", "collect", "c2", "c3", "e1",
    "a0", "a1", "a2", "a4", "a5", "a27", "a29", "s42", "s43", "s44", "s45",
    "s46", "s47", "seed42", "seg_model", "factor on", "t14-protocol-v7",
    "t14-protocol-v8", "dev9_v7_pixel", "dev_pixel_base",
    "active version = t14-protocol-v8",
    "minimal_risk", "planned_boundary_crossing", "F-F | F-E=1", "agent_src",
}

TRANS: dict[str, str] = {
    # ---- 标题 / suptitle -------------------------------------------------
    "(a) dev pool": "（a）开发池",
    "(a) dev pool (9 scenes, 117 frames)": "（a）开发池（9 场景，117 帧）",
    "(a) held-out final set, per group (label scope)": "（a）留出最终集，按组（标签范围）",
    "(a) lane/path availability in the baseline config": "（a）基线配置下的车道／路径可用率",
    "(a) the crossing is just inside the threshold": "（a）规划穿越恰好落在阈值之内",
    "(a) the factors do move the car": "（a）因子确实让车动了起来",
    "(a) travelled": "（a）行进距离",
    "(b) ...but none clears no_stall (=0 frames)": "（b）但没有一臂通过 no_stall（=0 帧）",
    "(b) 96% of those frames are stationary": "（b）这些帧中 96% 车辆静止",
    "(b) R3 limited-class pool": "（b）R3 有限类别池",
    "(b) negative side (n=200 frames)": "（b）负例一侧（n=200 帧）",
    "(b) stall fraction": "（b）停滞比例",
    "(b) why 202 lanes were revoked": "（b）202 条车道为何被撤销",
    "(dev) candidate lateral scope": "（开发）候选横向范围",
    "(dev) parallel merge": "（开发）并行合并",
    "(elong) threshold sensitivity": "（伸长）阈值敏感性",
    "(keep) threshold sensitivity": "（保留）阈值敏感性",
    "(R3) candidate lateral scope": "（R3）候选横向范围",
    "(R3) parallel merge": "（R3）并行合并",
    "Appearance gate ablation on the pixel metrics (seed 42)": "外观门消融对像素指标的影响（种子 42）",
    "Boundary map: dilation buys recall and pays precision \u2014 R3 pays ~3x more, so no single value clears both pools":
        "边界图：膨胀换来召回、付出精度——R3 的代价约为三倍，故无单一取值可同时通过两池",
    "Candidate-scope pipeline (schematic) and the measured revocation": "候选范围流水线（示意）与实测撤销率",
    "Closed-loop trade-off (town, 4 runs per arm): v8 takes the centre\ncrossings to zero; sensor-source rate is lower on median (ranges overlap)":
        "闭环权衡（城镇，每臂 4 次）：v8 把压中心线降到零；传感器来源率中位数更低（区间重叠）",
    "Counting contract v5 (schematic): every ratio has an explicit numerator and denominator":
        "计数契约 v5（示意）：每个比率都有显式分子与分母",
    "Deadlock anatomy: a parked, off-centre car is refused every path (12 town runs, current body inside in all frames)":
        "死锁解剖：停在中心之外的车辆被拒绝每一条路径（12 次城镇运行，全部帧中当前车体都在车道内）",
    "Dose response across five metrics (dev pool, per seed + mean)":
        "五个指标上的剂量响应（开发池，逐种子＋均值）",
    "Driving hard-gate checklist over the last 32 town runs (green = pass, red = fail; UNKNOWN counts as fail)":
        "最近 32 次城镇运行的驾驶硬门清单（绿=通过，红=未通过；UNKNOWN 计为未通过）",
    "Driving-layer single-factor ladder (town, alternating A/B, hard gates 0/4 in every arm)":
        "驾驶层单因子阶梯（城镇，交替 A/B，每臂硬门均 0/4）",
    "F-A hold window": "F-A 保持窗口",
    "F-C path recentre": "F-C 路径重定中",
    "F-D delivered arm": "F-D 交付感知臂",
    "F-E lane gate": "F-E 铺装门",
    "F-E lane-gate run (factor on) (ts 1791273507)": "F-E 铺装门运行（因子开，ts 1791273507）",
    "Final-set provenance audit: content-level overlap with the used set (407 used frame hashes)":
        "最终集来源审计：与已用帧集的内容级重叠（407 个已用帧哈希）",
    "GPU minutes (recorded ledger)": "GPU 分钟（已记录台账）",
    "Identity scope changes the reading, not the model\n(same checkpoints, 5 seeds per arm; dashed = 0.60 gate)":
        "身份范围改变的是读数而不是模型\n（同一批检查点，每臂 5 个种子；虚线 = 0.60 门）",
    "Instance-level reference coverage vs lateral offset (R3 certified scenes)":
        "实例级参考覆盖随横向偏移的变化（R3 已认证场景）",
    "Lane-acceptance evidence: the 'on-pavement' gate is driven by the BEV obstacle layer, not by 'off the pavement'":
        "车道接受证据：铺装门由 BEV 障碍层驱动，而不是由「不在铺装上」驱动",
    "Lane-placement deviation per frame (closed-loop round; black bar = median)":
        "逐帧车道放置偏差（闭环轮次；黑条 = 中位数）",
    "Lateral position of line markings relative to the lane centre (n=261042, median -0.174 m, |median| 1.222 m)":
        "标线相对车道中心的横向位置（n=261042，中位 −0.174 m，中位绝对偏移 1.222 m）",
    "Lateral-scope scan: identity/role vs threshold": "横向范围扫描：身份率／角色随阈值变化",
    "Negative-pool certification funnel (min paint px = 64, white v_min = 200)":
        "负例池认证漏斗（最小漆像素 = 64，白漆 v_min = 200）",
    "Negative-side diagnostics across 4 recorded arms (dev, seed 42; marker size = max CC px)":
        "负例一侧诊断，4 个已记录臂（开发，种子 42；标记大小 = 最大连通域 px）",
    "One-shot final confirmation (consumed once): delivered arm on a road-disjoint 200-frame set":
        "一次性最终确认（已消费一次）：交付臂在按道路切分的 200 帧集上",
    "One-shot final confirmation flow (schematic) and the live seal":
        "一次性最终确认流程（示意）与实时封存信息",
    "Pairing availability under the two definitions (label: frames lost by the adopted scope)":
        "两套定义下的配对可用率（标签范围：被采纳范围损失的帧）",
    "Parallel-merge scan: what merging removes, and what it costs": "并行合并扫描：合并移除了什么，代价是什么",
    "Per-arm distributions (town A/Bs, 4 runs per arm)": "各臂分布（城镇 A/B，每臂 4 次运行）",
    "Per-run time series: speed (top) and path-to-lane deviation (bottom); dashed = 0.5 m/s stall threshold":
        "逐运行时间序列：速度（上）与路径到车道偏差（下）；虚线 = 0.5 m/s 停滞阈值",
    "Protocol switch matrix (schematic) and the live hash": "协议开关矩阵（示意）与实时哈希",
    "R2 acceptance: the two protocol definitions each fail a different gate":
        "R2 验收：两套协议定义各自失败在不同的门上",
    "R3 limited-class pool, per seed: candidate-level gates (x = below gate; label scope)":
        "R3 有限类别池逐种子：候选级门（x = 低于门；标签范围）",
    "Recorded GPU-time ledger (three logged days) by task family": "已记录的 GPU 时间台账（三个有记录的日子）按任务族",
    "SWA (last-5-epoch mean)": "SWA（末 5 轮均值）",
    "SWA single-factor result: no seed is rescued\n(rejected; dashed = 0.70 recall gate)":
        "SWA 单因子结果：没有种子被救回\n（已否决；虚线 = 0.70 召回门）",
    "Safety arbitration ladder (schematic, from ARBITRATION_RULES)":
        "安全仲裁阶梯（示意，取自 ARBITRATION_RULES）",
    "Safety-margin distributions over 4 acceptance runs (settled frames)":
        "4 次验收运行的安全裕度分布（已结算帧）",
    "Scene screening criterion: structure density of the certified pools (black bar = median)":
        "场景筛选准则：已认证池的结构密度（黑条 = 中位数）",
    "Sealed final set composition (n=200, digest 798f84883eb75bde, protocol f5ec944c5dd23b44)":
        "封存最终集组成（n=200，摘要 798f84883eb75bde，协议 f5ec944c5dd23b44）",
    "Spatial-isolation audit (buffer 50.0 m; dev frames with pose = 757; all isolated = True)":
        "空间隔离审计（缓冲 50.0 m；开发帧含位姿 = 757；全部隔离 = True）",
    "Threshold sensitivity of the mask post-processing": "掩码后处理的阈值敏感性",
    "Timing hygiene: repeated inference on a quiet machine (game running = False, gpu util = 0.0)":
        "计时卫生：安静机器上的重复推理（仿真器运行 = False，GPU 占用 = 0.0）",
    "Training curves by family (321 recorded runs, 44 families; top 10 shown)":
        "按家族分组的训练曲线（321 次已记录运行，44 个家族；显示前 10）",
    "Training-composition dose response: identity peaks at 6x, saturates at 8.5x":
        "训练组成剂量响应：身份率在 6× 处出现峰值，8.5× 处饱和",
    "Tversky beta=0.8 arm vs base: the negative side gets worse (R3 pool, seed 42)":
        "Tversky β=0.8 臂对比基线：负例一侧变差（R3 池，种子 42）",
    "Where the two recall scopes disagree (dev pool, 6 seeds)": "两种召回范围在哪里不一致（开发池，6 个种子）",
    "Why the car does not move: safety-arbitration reasons": "车为什么不动：安全仲裁原因",
    "Why the safety rule needed re-specifying: raw frame counts scale with\nhow far the car moved (factor arms move 2x further)":
        "安全规则为何需要重新表述：原始帧计数随行进距离缩放\n（因子臂行进距离为两倍）",
    "a refused access is recorded but does not consume; a consumed set is a diagnostic set (freeze a new one)":
        "被拒绝的访问只记录、不消费；已消费的集合只能用于诊断（需另封存一个）",
    "bars are normalised for display; raw values are labelled on the bars":
        "柱高已归一化显示；原始数值标在柱上",
    "dev: the recall gate fails for 1/6 seeds at 0 px (s45 = 0.671)   |   R3: precision 0.39 and role 0.66 fall below their gates at 1 px":
        "开发：0 px 时有 1/6 种子召回不达标（s45 = 0.671）   |   R3：1 px 时精度 0.39 与角色 0.66 低于其门",
    "gates (mean over seeds):\n  coverage = R / C      identity = M / R\n  role     = A / L      precision/recall = pixels":
        "各门（跨种子均值）：\n  覆盖率 = R / C      身份率 = M / R\n  角色     = A / L      精度／召回 = 像素级",
    "line-masked runs: IoU = 0 by construction\nt14_entry_accept (12), t14_auto_20260925_steps (10), t14_auto_20260925_width2 (10) ...":
        "线通道被屏蔽的运行：按构造 IoU = 0\nt14_entry_accept（12）、t14_auto_20260925_steps（10）、t14_auto_20260925_width2（10）……",
    "measured (2026-10-06, town driving): 34% of paired frames revoked by the on-pavement gate\nthe revoking term was the BEV obstacle layer, not 'off the pavement' (202/202 frames)":
        "实测（2026-10-06，城镇驾驶）：34% 的配对帧被铺装门撤销\n撤销项是 BEV 障碍层，而不是「不在铺装上」（202/202 帧）",
    "negative side not measurable here\n(R3 pool: no eligible negative frames)":
        "此处负例一侧不可测\n（R3 池：没有合格负例帧）",
    "soft rules accumulate caps; a minimal_risk rule stops the tick (order is the evaluated order, not severity)":
        "软规则累积速度上限；最坏等级为 minimal_risk 的规则停止该节拍（顺序为评估顺序，非严重度）",
    "the obstacle term does the revoking; off-mask ≈ 0": "撤销全部来自障碍项；掩码外样本 ≈ 0",
    "worst-case body-centre-cross frames (control\u2192factor): 29\u219230 / 84\u219239 / 36\u219249 / 23\u219266 / 23\u219231":
        "最坏车体中心穿越帧（对照→因子）：29→30 / 84→39 / 36→49 / 23→66 / 23→31",
    "y-axis truncated at 0.40": "纵轴在 0.40 处截断",
    "a consumed set is a diagnostic set (freeze a new one)": "已消费的集合只能用于诊断（需另封存一个）",
    "A \u2286 L\nrole\nagreed": "A ⊆ L\n角色\n一致",
    "C\ncandidate instances\n(extracted)": "C\n候选实例\n（抽取）",
    "C_outside_P\ncandidates on frames\noutside P": "C_outside_P\n落在 P 之外帧上的候选",
    "L \u2286 M\nlateral\nagreed": "L ⊆ M\n横向\n一致",
    "M \u2286 R\nmatched": "M ⊆ R\n匹配",
    "P_frames\nframes with\na candidate": "P_frames\n含候选的帧",
    "R \u2286 C\nreference instances\n(annotation truth)": "R ⊆ C\n参考实例\n（标注真值）",
    "F-A\noff": "F-A\n关",
    "F-A\non": "F-A\n开",
    "F-C\noff": "F-C\n关",
    "F-C\non": "F-C\n开",
    "F-E\noff": "F-E\n关",
    "F-E\non": "F-E\n开",
    "F-A-off": "F-A-关",
    "F-A-on": "F-A-开",
    "F-C-off": "F-C-关",
    "F-C-on": "F-C-开",
    "F-E-off": "F-E-关",
    "F-E-on": "F-E-开",
    "F-F | F-E=1": "F-F | F-E=1",
    # ---- 轴标签 ----------------------------------------------------------
    "access gate\n(protocol hash)": "访问门\n（协议哈希）",
    "annotation coverage (mean)": "标注覆盖率（均值）",
    "body-centre-cross frames (max)": "车体中心穿越帧（最大）",
    "candidate identity rate": "候选身份率",
    "cells per revoked frame": "每个撤销帧的单元数",
    "centre-crossing frames (reference line)": "压中心线帧（按参考线）",
    "closest obstacle (m)": "最近障碍（m）",
    "dose (x)": "剂量（×）",
    "ego speed (m/s)": "本车速度（m/s）",
    "elong threshold": "伸长阈值",
    "epoch": "轮次",
    "false-positive frame rate": "假阳性帧率",
    "false-positive pixels (% of eligible)": "假阳性像素（占合格像素 %）",
    "frames": "帧数",
    "frames (12 town runs, 2443 settled frames)": "帧（12 次城镇运行，2443 个已结算帧）",
    "frames (2 baseline diagnostic runs)": "帧（2 次基线诊断运行）",
    "frames (n=512)": "帧（n=512）",
    "frames (total 85)": "帧（合计 85）",
    "frames with a paired lane": "含配对车道的帧",
    "frames with pose": "含位姿的帧",
    "frozen gate": "冻结门",
    "gate metric (mean over 6 seeds)": "门指标（6 种子均值）",
    "inference latency (ms)": "推理延迟（ms）",
    "keep threshold": "保留阈值",
    "label line pixels that are NOT paint": "标签线像素中非漆的比例",
    "label non-paint frac": "标签非漆比例",
    "label scope": "标签范围",
    "lateral offset of the reference instance (m)": "参考实例的横向偏移（m）",
    "lateral scope threshold (m)": "横向范围阈值（m）",
    "line IoU": "线 IoU",
    "line precision": "线精度",
    "line recall": "线召回",
    "mask dilation (px)": "掩码膨胀（px）",
    "max CC\n(px/2000)": "最大连通域\n（px/2000）",
    "max CC (px)": "最大连通域（px）",
    "merge groups": "合并组",
    "metric": "指标",
    "metric (R3 pool, seed 42)": "指标（R3 池，种子 42）",
    "metric (mean over 6 seeds)": "指标（6 种子均值）",
    "metric (per seed)": "指标（逐种子）",
    "min TTC (s)": "最小 TTC（s）",
    "near-field structure density": "近场结构密度",
    "negative-example dose (x, relative to the base pool)": "负例剂量（×，相对基础池）",
    "normalised value": "归一化值",
    "off-road candidate fraction": "路外候选比例",
    "candidates": "候选",
    "dev (reviewed)": "开发（人工修订）",
    "dev > 0.30 m": "开发 > 0.30 m",
    "lane boundary recovery": "车道边界恢复",
    "0.52 x": "0.52 ×", "0.55 x": "0.55 ×", "0.56 x": "0.56 ×", "0.58 x": "0.58 ×",
    "0.59 x": "0.59 ×", "0.67 x": "0.67 ×", "0.69 x": "0.69 ×",
    "parallel-merge radius (m)": "并行合并半径（m）",
    "path occupancy fraction": "路径占用比例",
    "path-to-lane deviation (m)": "路径到车道偏差（m）",
    "per 100 m travelled": "每 100 m 行进",
    "pixel metric": "像素指标",
    "planned crossing distance (m)": "规划穿越距离（m）",
    "raw max frames": "原始最大帧数",
    "same, per 100 m travelled": "同一量，每 100 m 行进",
    "sensor lane-source rate (fraction of frames)": "传感器车道来源率（占帧比例）",
    "speed (m/s)": "速度（m/s）",
    "stall fraction": "停滞比例",
    "stall fraction (median)": "停滞比例（中位数）",
    "t (s)": "t（s）",
    "train loss (median, IQR band)": "训练损失（中位数，IQR 带）",
    "travelled (m)": "行进（m）",
    "travelled (m, median of 4 runs)": "行进（m，4 次运行中位数）",
    "val line IoU (median, IQR band)": "验证线 IoU（中位数，IQR 带）",
    "obstacle\ncells": "障碍\n单元",
    "off-mask\ncells": "掩码外\n单元",
    # ---- 图例 / 分类刻度 ------------------------------------------------
    "adopted (no SWA)": "采纳（无 SWA）",
    "adopted 5.5": "采纳值 5.5",
    "adopted definition": "采纳定义",
    "appearance gate": "外观门",
    "appearance gate\npaint-like": "外观门\n类漆",
    "appearance off": "外观关",
    "appearance on": "外观开",
    "base (dilate 1)": "基线（膨胀 1）",
    "baseline definition": "基线定义",
    "baseline acceptance run (ts 1791221139)": "基线验收运行（ts 1791221139）",
    "beta=0.8 (Tversky)": "β=0.8（Tversky）",
    "certified\nnegative": "已认证\n负例",
    "contains paint\n(excluded)": "含漆\n（排除）",
    "control": "对照",
    "coverage": "覆盖率",
    "identity": "身份率",
    "identity gate 0.60": "身份门 0.60",
    "kept": "保留",
    "lat <= 5.5 m": "横向 ≤ 5.5 m",
    "lat = 0 (off)": "横向 = 0（关）",
    "lateral scope\n|lat| <= 5.5 m": "横向范围\n|横向| ≤ 5.5 m",
    "merge (same-side,\nr = 1.0 m)": "合并（同侧，\nr = 1.0 m）",
    "merge-final off": "合并-最终 关",
    "merge-final on": "合并-最终 开",
    "merged away": "被合并",
    "marking pixels": "标线像素",
    "no centre X": "无压中心线",
    "no collision": "无碰撞",
    "no drivable path": "无可用路径",
    "no edge X": "无压边线",
    "no reversing": "无倒车",
    "no stall": "无停滞",
    "on road": "在路",
    "other": "其他",
    "paint scope": "漆范围",
    "path exists": "路径存在",
    "path hold (creep)": "路径保持（蠕动）",
    "precision": "精度",
    "recall": "召回",
    "recall (paint scope)": "召回（漆范围）",
    "recall (paint)": "召回（漆）",
    "role": "角色",
    "seal\n(content digest)": "封存\n（内容摘要）",
    "sensor lane": "传感器车道",
    "settled": "已结算",
    "straddled": "跨越",
    "surface scope": "表面范围",
    "suspect\n(excluded)": "可疑\n（排除）",
    "undecided\n(excluded)": "未决\n（排除）",
    "v7 (frozen)": "v7（冻结）",
    "v7 (label scope)": "v7（标签范围）",
    "v7 closed-loop": "v7 闭环",
    "v8 (adopted)": "v8（采纳）",
    "v8 (label scope)": "v8（标签范围）",
    "v8 (paint scope, adopted)": "v8（漆范围，采纳）",
    "v8 closed-loop": "v8 闭环",
    "goal reached": "到达目标",
    "obstacle contact risk": "障碍接触风险",
    "obstacle stopping distance": "障碍停车距离",
    "obstacle very close": "障碍很近",
    "planned boundary crossing ahead": "前方规划边界穿越",
    "planned vehicle body crosses lane boundary": "规划车体穿越车道边界",
    "scattered obstacle": "散布障碍",
    "stale_sensor_planner": "传感器／规划过期",
    "stationary_recentre": "静止重定中",
    "path_blocked": "路径被阻断",
    "path_grazes": "路径擦边",
    "path_hold": "路径保持",
    "path_near_lane_edge": "路径贴近车道边缘",
    "path_off_lane": "路径离开车道",
    "perception_lane_unavailable": "感知车道不可用",
    "body_crosses_boundary": "车体穿越边界",
    "body_off_pavement": "车体离开铺装",
    "lane_boundary_recovery": "车道边界恢复",
    "lane_dev (m)": "车道偏差（m）",
    "road_surface": "可行驶表面",
    "no_drivable_path": "无可用路径",
    "obstacle_risk": "障碍风险",
    "obstacle_very_close": "障碍很近",
    "scattered_obstacle": "散布障碍",
    "far_left": "远左",
    "near_left": "近左",
    "near_right": "近右",
    "compose\n(road-disjoint)": "组成\n（道路不相交）",
    "consumed\n(no re-read)": "已消费\n（不可再读）",
    "evaluate once\n(pixels)": "评测一次\n（像素）",
    "final candidate set\n(v7/v8)": "最终候选集\n（v7/v8）",
    "mask\ncandidates": "掩码\n候选",
    "already used (content-level overlap)": "已使用（内容级重叠）",
    "bar = median": "黑条 = 中位数",
    "4 m hard-stop\nthreshold": "4 m 硬停\n阈值",
    "FP frames\n(rate)": "假阳性帧\n（比率）",
    "FP frames (rate)": "假阳性帧（比率）",
    "FP pixels": "假阳性像素",
    "FP pixels\n(% of eligible)": "假阳性像素\n（占合格 %）",
    "n measured = 54": "实测 n = 54",
    "n measured = 60": "实测 n = 60",
    "1164 px": "1164 px",
    "2426 px": "2426 px",
    "28 min": "28 min",
    "37 min": "37 min",
    "210 min": "210 min",
    "run 1\n(117 frames)": "运行 1\n（117 帧）",
    "run 2\n(117 frames)": "运行 2\n（117 帧）",
    "run 3\n(117 frames)": "运行 3\n（117 帧）",
    "a0\n(n=32)": "a0\n（n=32）",
    "a1\n(n=16)": "a1\n（n=16）",
    "a2\n(n=16)": "a2\n（n=16）",
    "a4\n(n=8)": "a4\n（n=8）",
    "a5\n(n=104)": "a5\n（n=104）",
    "a27\n(n=16)": "a27\n（n=16）",
    "a29\n(n=8)": "a29\n（n=8）",
    "seed42\nrep0": "seed42\nrep0",
    "seed42\nrep1": "seed42\nrep1",
    "seed42\nrep2": "seed42\nrep2",
    "seg_model\nrep0": "seg_model\nrep0",
    "seg_model\nrep1": "seg_model\nrep1",
    "seg_model\nrep2": "seg_model\nrep2",
}

PHRASES: list[tuple[str, str]] = [
    ("sealed frames = ", "封存帧 = "),
    ("confirmations = ", "确认次数 = "),
    ("digest = ", "摘要 = "),
    ("protocol = ", "协议 = "),
    ("protocol hash = ", "协议哈希 = "),
    ("active version = ", "启用版本 = "),
    ("(fraction of frames)", "（占帧比例）"),
    ("per seed + mean", "逐种子＋均值"),
    ("mean over 6 seeds", "6 种子均值"),
    ("mean over seeds", "跨种子均值"),
    ("median of 4 runs", "4 次运行中位数"),
    ("black bar = median", "黑条 = 中位数"),
    ("(median, IQR band)", "（中位数，IQR 带）"),
    ("dashed = ", "虚线 = "),
    ("label scope", "标签范围"),
    ("paint scope", "漆范围"),
    ("per seed", "逐种子"),
    ("median", "中位数"),
    ("(frames)", "（帧）"),
    ("frames", "帧"),
    ("(m/s)", "（m/s）"),
    ("(ms)", "（ms）"),
    ("(px)", "（px）"),
    ("(s)", "（s）"),
    ("(m)", "（m）"),
    ("(x", "（×"),
]
